import localFont from "next/font/local";
import "./globals.css";
import { GridBackgroundDemo } from "@/components/common/gridBackground";
import Navbar from "@/components/ui/navbar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Bryan Sigala",
  description: "Generated by create next app",
};

const content = {
  text: {
    about: "About Me",
    projects: "Projects",
    experience: "Experience",
    contact: "Contact"
  },
  cvText: "Download CV", 
  cvLink: "",
  socialLinks: {
    linkedin: "https://www.linkedin.com/in/bryan-sigala/", 
    github: "https://github.com/StellarDBryan", 
    x: "https://x.com/BSigala16",
  }
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-x-hidden`}
      >
        <header>
          <Navbar content={content.text} cvText={content.cvText} cvLink={content.cvLink} socialLinks={content.socialLinks} />
        </header>
        <GridBackgroundDemo />
        {children}
      </body>
    </html>
  );
}
